name: appChallenge
channels:
  - esri
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - jupyter_nbextensions_configurator 
  - geopandas
  - descartes
  - h3[version='>=3.6.1']
  - pandas
  - h3-py
  - rtree=0.9.3
  - arcgis
prefix: C:\Users\mpr_1\miniconda3\envs\appChallenge
